//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProjesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StajProjeEntities2 : DbContext
    {
        public StajProjeEntities2()
            : base("name=StajProjeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adre> Adres { get; set; }
        public virtual DbSet<Indirim> Indirims { get; set; }
        public virtual DbSet<KartBilgisi> KartBilgisis { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Manset> Mansets { get; set; }
        public virtual DbSet<MesajBox> MesajBoxes { get; set; }
        public virtual DbSet<Resimler> Resimlers { get; set; }
        public virtual DbSet<SatısBilgi> SatısBilgi { get; set; }
        public virtual DbSet<SepetBilgi> SepetBilgis { get; set; }
        public virtual DbSet<SepetUrunler> SepetUrunlers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
    }
}
