//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.SepetUrunlers = new HashSet<SepetUrunler>();
        }
    
        public int id { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string ResimYol { get; set; }
        public string Fiyat { get; set; }
        public Nullable<int> Kategori { get; set; }
        public Nullable<int> Resimid { get; set; }
        public Nullable<int> Yöneticiid { get; set; }
        public Nullable<int> Indirimid { get; set; }
        public Nullable<int> Sepetid { get; set; }
    
        public virtual Indirim Indirim { get; set; }
        public virtual Login Login { get; set; }
        public virtual SepetBilgi SepetBilgi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SepetUrunler> SepetUrunlers { get; set; }
    }
}
